name: Envoi vers OVH
on:
  push:
    branches:
      - main  # Le nom de ta branche principale (parfois c'est 'master')
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
     - name: Installer et Construire le Frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # C'est ici que ça change :
          # On prend le résultat du dossier 'dist' qui a été créé 
          # (si 'dist' ne marche pas, on essaiera avec 'build')
          local-dir: ./frontend/dist/ 
          server-dir: ./www/
