name: Deploy Emergent Site to OVH
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Checkout du code
        uses: actions/checkout@v3

      - name: ğŸ—ï¸ Installer et Construire le Frontend
        working-directory: ./frontend
        run: |
          # Nettoyage et installation forcÃ©e
          rm -rf node_modules package-lock.json
          npm install ajv --save-dev --legacy-peer-deps
          npm install --legacy-peer-deps
          npm run build

      - name: ğŸš€ FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # Craco crÃ©e un dossier 'build'
          local-dir: ./frontend/dist/
          server-dir: ./www/
          delete-destination: false
