name: Deploy Emergent Site to OVH
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Tentative de Construction (Build)
        working-directory: ./frontend
        # On ajoute '|| true' pour que le robot continue mÃªme s'il y a une petite erreur
        run: |
          npm install || true
          npm run build || true

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # On essaie d'envoyer le dossier 'dist', s'il n'existe pas, 
          # on envoie directement le dossier 'public'
          local-dir: ./frontend/public/
          server-dir: ./www/
